# Generated by Django 6.0.6 on 2026-06-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accumulated_point',
            field=models.IntegerField(default=3500),
        ),
    ]
