# Generated by Django 6.0.6 on 2026-06-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pot_is_completed_pot_start_date_proof_is_valid_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='auth_days',
            field=models.CharField(default='mon,tue,wed,thu,fri,sat,sun', max_length=30),
        ),
        migrations.AddField(
            model_name='potavatar',
            name='item_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
